### ISSUE TITLE
can't work on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by Bald-Badger** [martpie/museeks#634] opened 2022-05-05 04:27 UTC
just installed a new Ubuntu 22.04 (and i hate it so much because now all my serial devices are not working)
Anyways I tried to open museeks. I'm really a noob in computer so I'm just gonna put the error message here.
Honestly I'm not really sure if its really an issue or I crushed something in my linux
```(base) luke@Shubuntu:~$ museeks 
[INFO] Skipping load of ThumbarModule
[INFO] Skipping load of DockMenuDarwinModule
(node:21645) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `museeks --trace-deprecation ...` to show where the warning was created)
[21645:0505/002354.786307:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```

**Comment by AntiGuide** [comment] 2022-05-08 15:25
This seems to be a duplicate of https://github.com/martpie/museeks/issues/630
You can `sudo nano /usr/share/applications/museeks.desktop` and change
`Exec=/opt/Museeks/museeks %U`
to
`Exec=/opt/Museeks/museeks --disable-gpu-sandbox %U`

**Comment by martpie** [comment] 2022-05-08 15:49
Thank you very much for providing a workaround! I will have a look as it is most probably an upstream bug. 

I should do a small release with small changes soon, hopefully it will fix it 😬

**Comment by martpie** [comment] 2022-05-13 23:11
Does the latest release fix it?

**Comment by AntiGuide** [comment] 2022-05-14 08:51
@martpie Yes it launches perfectly on my machine! Thank you very much.

**Closed** 2022-05-14 09:44 UTC
