### ISSUE TITLE
Library import stalle when app not focused

### ISSUE THREAD

**Issue by vprigent** [martpie/museeks#424] opened 2018-03-18 21:39 UTC
Hi all.

That is something I have already noticed. When we try to import a lib, it can take some time, so we usually switch to another window but then, the import seems to pause completely, the only solution is to focus Museeks.

Do you know where it could come from ?
I think this has already been discussed but I coulnd find an issue talking about this.

**Comment by KeitIG** [comment] 2018-03-18 22:31
I've noticed this too

**Comment by vprigent** [comment] 2018-03-18 23:25
I could easily see something related to how Chrome tries to reduce its processor footprint when its not focused...

**Comment by KeitIG** [comment] 2018-03-18 23:26
Maybe moving the library refresh to a worker would help

**Comment by KeitIG** [comment] 2018-04-24 11:36
I could not reproduce it lately with the latest versions of Museeks, can you?

**Comment by vprigent** [comment] 2018-04-24 11:56
I just tried it by resetting and doing an import, if I close the window or reduce it, the sync does not go on. 
Tried on Macbook Pro mid 2012, OSX 10.12.6.
Museeks version : 0.9.4

**Comment by KeitIG** [comment] 2018-04-24 11:59
darn, thanks, I'll look at that more in details and how we can possibly fix it.

**Comment by vprigent** [comment] 2018-09-07 10:00
Could not reproduce on Ubuntu 18.04 :+1:

**Comment by martpie** [comment] 2018-09-07 11:34
Let's close it and re-open it if needed then :)

**Closed by martpie** 2018-09-07 11:34 UTC
Labels: bug, confirmed
