### ISSUE TITLE
hotkeys

### ISSUE THREAD

**Issue by DennisDray** [martpie/museeks#466] opened 2018-12-13 22:11 UTC
the keyboard play/pause, next/ previous buttons should control the player
also, a panel indicator with those controls would be great, like panflute had it back in the day
handy when your laptop is in tablet mode

**Comment by martpie** [comment] 2018-12-13 23:37
Playback hotkeys should be working. What is the laptop/PC you are using?

I don’t get the panel indicator thing, so you have a screenshot or more details for me please?

**Comment by martpie** [comment] 2018-12-15 05:44
Let’s assume it’s a duplicate of 
https://github.com/martpie/museeks/issues/431.

Feel free to contest.

**Closed by martpie** 2018-12-15 05:44 UTC
