### ISSUE TITLE
Pause music on headphone unplug

### ISSUE THREAD

**Issue by JAYRANRAIN** [martpie/museeks#464] opened 2018-12-09 12:28 UTC
I really like the playback software you designed, it has been used for half a year. But today I noticed a problem in the process of using it.
I hope that you can add a function, that is, when listening to music with headphones, if you remove the headphones, the music can stop playing.

**Comment by martpie** [comment] 2018-12-09 19:43
Thank you for the feedback. Out of curiosity, do you know any other music player that integrates this feature?

**Comment by JAYRANRAIN** [comment] 2018-12-15 13:36
Indeed, many music players are unplugged and have sound  on linux. I am currently using elementary os 5.0 juno, I tried the music player that comes with this system, when it is unplugged, it automatically stops playing (I haven't used it to tell you the truth).

**Comment by martpie** [comment] 2018-12-15 19:42
Electron does not provide an API to detect this change, so I cannot so much today. It is also less trivial than it looks: Bluetooth headphones should behave the same too.

To me, this is a is-level problem, and not an app-problem. Let’s see how this evolves.

**Comment by rhysperry111** [comment] 2019-05-12 14:52
I don't know much about electron but it is relatively easy to detect headphone actions. Whenever headphones are unplugged/plugged most modern devices send out an ACPI call. As i am not a developer i am not sure how easy it would be for your app to access ACPI calls.

**Comment by martpie** [comment] 2019-05-12 15:08
> but it is relatively easy to detect headphone actions

> most modern devices send out an ACPI call

The problem is we need to support 3 platforms, not only Linux.

**Comment by martpie** [comment] 2019-05-12 15:12
Plus, I stick with my belief that this should be an OS feature, and music players should not have to worry about this kind of things: the os should either set the volume to 0 or send a global play/pause event.

**Comment by martpie** [comment] 2019-07-22 08:59
Closing for cause of non-feasibility. This should be done at the OS level to at least mute the sound when headphones are unplugged

**Closed by martpie** 2019-07-22 08:59 UTC
Labels: blocked, discussion, enhancement
