### ISSUE TITLE
Failure to add music library?

### ISSUE THREAD

**Issue by adamltaylor** [martpie/museeks#522] opened 2020-03-25 01:49 UTC
This looks like a great project, but I'm having trouble adding my music library to it.  My music library has one folder per artist, and within each artist folder it has one folder per album, and then .mp3's within those.  When I drag-and-drop the music folder into the "Import music" rectangle under Gear > Library, nothing seems to happen.  My music folder is about 20 GB.

If I drag-and-drop one of the album folders into Museeks, I get the same result: nothing happens.

If I drag-and-drop a bunch of .mp3 files into Museeks, that works, and the songs show up in the 'playlist' tab (not sure if that's the proper name).

Hypothetically, I could copy all my .mp3's into a single folder, and then drag-and-drop them into museeks, but that's a bit of a hassle.

Is what I'm seeing the intended behavior, or is this a bug?

I'm trying this in Museeks 0.11.3, in Windows 10 Pro 1903.

**Comment by martpie** [comment] 2020-03-25 08:52
Hello there! 

It looks like a bug, can you try to click on the "Import music" dropzone and try to import your music folder with the file/directory picker dialog and tell me if it works?

**Comment by adamltaylor** [comment] 2020-03-25 14:02
I'm afraid clicking on the "Import music" dropzone and using the file/folder picker seems to give the same result: no new songs appearing in the main tab...

**Comment by martpie** [comment] 2020-03-25 14:04
😱 I will test on Windows, it's working fine on macOS

**Comment by adamltaylor** [comment] 2020-03-25 14:19
Kind of you to look into it!

**Comment by martpie** [comment] 2020-03-25 15:26
I can reproduce it D: 

Will try to fix asap

**Comment by martpie** [comment] 2020-03-25 16:34
Fixed in 0.11.4, sorry for the inconvenience :c 

Binaries are uploaded, updated website is being deployed right now.

**Closed by martpie** 2020-03-25 16:34 UTC

**Comment by adamltaylor** [comment] 2020-03-25 17:37
Wow!  Thank you so much for fixing this!
